FROM node:16-alpine

WORKDIR /frontend

# Copy package.json and package-lock.json first to leverage Docker caching
COPY package*.json ./

# Install dependencies
RUN npm install

RUN npm install -g @vue/cli

COPY . .

EXPOSE 7722

# Default command to start the Vue dev server
CMD ["npm", "run", "serve"]
