FROM node:16-alpine

WORKDIR /frontend

# Copy only package.json and package-lock.json (or yarn.lock) for dependency installation
COPY package*.json ./

RUN npm install

EXPOSE 8080

# Default command to run the development server
CMD ["npm", "run", "serve"]